// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qiSt09gvhHZYVGB1fMOZ7yhGqy8GxO8',
    appId: '1:189855047664:android:3f67dd8808051513464735',
    messagingSenderId: '189855047664',
    projectId: 'spa-app-fd0f3',
    storageBucket: 'spa-app-fd0f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8M94JX7cBERT2M0HFS_drXxwfhWGPDQ',
    appId: '1:189855047664:ios:722743a5b255553b464735',
    messagingSenderId: '189855047664',
    projectId: 'spa-app-fd0f3',
    storageBucket: 'spa-app-fd0f3.appspot.com',
    iosClientId: '189855047664-fq48edugpaoqioqqd76a3b2sgj7bq8e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.namTraining',
  );
}
